version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Run Docker
          command: docker-compose up -d
      - run:
          name: Preapre environment variables
          command: cp .env.example .env
      - run:
          name: Install PHP dependencies
          command: docker-compose run composer sh -c "composer install && composer dump-autoload --optimize"
      - run:
          name: Install NodeJS dependencies
          command: docker-compose run node sh -c "yarn install && yarn run prod"
      - run:
          name: Start processing jobs on the queue
          command: docker-compose run -d php sh -c "php artisan queue:work redis"
      - run:
          name: Start the Laravel WebSocket Server
          command: docker-compose run -d php sh -c "php artisan websockets:serve"
      - run:
          name: Prepare the database
          command: |
            docker-compose run php sh -c "wait-for-it.sh db:3306"
            docker-compose run php sh -c "php artisan key:generate --env=testing --no-interaction"
            docker-compose run php sh -c "php artisan migrate --env=testing --no-interaction"
            docker-compose run php sh -c "php artisan db:seed --env=testing --no-interaction"
      - run:
          name: Run tests
          command: docker-compose run php bash -c "php artisan test"
